name: Artifact Example

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create an example file
        run: echo "This is an artifact file" > example.txt

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: example.txt
          retention-days: 5  # Optional: Set retention period
          
  download:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: my-artifact
          path: downloaded-files  # Optional: Save artifact in a specific folder

      - name: Verify Artifact
        run: cat downloaded-files/example.txt
