name: Caching Example

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Cache npm Modules
        uses: actions/cache@v4
        with:
          path: application/node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('application/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install Dependencies
        run: npm install
        working-directory: application

      - name: Build Project
        run: npm run build
        working-directory: application
