name: Call Reusable Workflow

on:
  workflow_dispatch:
    inputs:
      runner:
        description: "Runner to execute the workflow"
        required: true
        type: choice
        options:
          - ubuntu-latest
          - windows-latest
          - macos-latest

jobs:
  call-reusable:
    uses: ./.github/workflows/reusable_workflow.yaml
    with:
      runner: ${{ inputs.runner }}  # Pass the selected runner
