name: CI Example
on: 
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: 'Choose the environment'
jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Print environment
        shell: bash
        run: echo 'Environment: ${{ inputs.environment }}'
