name: Input Example

on: 
  workflow_dispatch:
    inputs:
      username:
        description: 'Enter your name'
        required: true
      deploy:
        description: 'Deploy the application?'
        required: true
        type: boolean

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: Print Inputs
        run: |
          echo "Hello, ${{ inputs.username }}!"
          echo "Deploy: ${{ inputs.deploy }}"
