name: Lint and Format with Ruff

on:
  push:

  pull_request:
  
  workflow_dispatch:

jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Ruff
        run: pip install ruff

      - name: Run Ruff Linter
        run: ruff check .  # Check for linting errors

      - name: Run Ruff Formatter
        run: ruff format .  # Auto-fix code styling issues

      - name: Fail if Linting Issues Exist
        run: |
          if ! ruff check --exit-zero .; then
            echo "Linting errors found! Please fix them."
            exit 1
          fi
