name: Parallelism and Concurrency

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: build-group
      cancel-in-progress: true
    steps:
      - run: echo "Building the app"

  test:
    runs-on: ubuntu-latest
    concurrency:
      group: test-group
      cancel-in-progress: true
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node: [18, 20]
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - run: echo "Testing on ${{ matrix.os }} with Node.js ${{ matrix.node }}"
