name: Concurrency

on: push
jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: build-group
      cancel-in-progress: true
    steps:
      - run: echo "Building the app"
      - run: sleep 60
