name: Advanced Event Workflow

on:
  push:
    branches:
      - main  

  pull_request:
    types:
      - opened
      - reopened
      - synchronize  

  workflow_dispatch:  

jobs:
  analyze-event:
    name: Analyze Event and Context
    runs-on: ubuntu-latest
    steps:
      - name: Print Event Info
        run: |
          echo "Event Name: ${{ github.event_name }}"
          echo "Action: ${{ github.event.action || 'N/A' }}"
          echo "Repository: ${{ github.repository }}"
          echo "Branch/Tag: ${{ github.ref }}"
          echo "Workflow Triggered By: ${{ github.actor }}"

      - name: Detect Push to Main Branch
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        run: echo "This is a push to the main branch."

      - name: Display Files Modified (for PR events)
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          echo "Files changed in this PR:"
          git fetch origin ${{ github.event.pull_request.base.ref }} --depth=1
          git diff --name-only origin/${{ github.event.pull_request.base.ref }}

  run-specific-task:
    name: Run Task on Specific Conditions
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'push' }}
    steps:
      - name: Triggered by Workflow Dispatch or Push
        run: echo "Running task due to a manual trigger or a push to the main branch."
